FROM python:3.11-alpine
RUN apk add --no-cache bash g++
WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY . /app
ENV vulnerable=1
ENTRYPOINT ["python", "_wave_entry.py", "app.py"]
