"""Gates for picking a real security guard out of a JavaScript patch.

Follows docs/TS_DATA_STANDARD.md. Built by REUSING the validated line-level logic
from `ts_guard_gates` -- those seven gates were each derived from an observed
defect and regression-checked against 223 hand-vetted guards -- and replacing only
the parts that are genuinely language-specific.

What differs for JavaScript, and why:

  PATHS. Extensions are .js/.jsx/.mjs/.cjs. Test naming is the same convention
  (`foo.test.js`, `__tests__/`), but BUNDLES are a far bigger problem than in TS:
  npm packages ship built output, so `dist/`, `lib/`, `umd/`, `.min.js` and
  vendored copies are common in the same repo as the source. A minified bundle puts
  a whole module on one line and the guard-picker then quotes a namespace
  initialiser as a security control -- that exact defect cost three pairs in the
  earlier cross-file work.

  BUILT OUTPUT. `dist/index.js` is frequently a COMPILED copy of `src/index.ts`.
  Including it would duplicate a record and attribute the guard to generated code,
  so build directories are excluded even when they contain real logic.

JS-SPECIFIC LINE GATES ARE ADDED ONLY AS THEY ARE OBSERVED, never guessed --
`_JS_EXTRA` starts empty and is filled from inspection.
"""
import re

# Reuse the validated line-level logic rather than re-deriving it.
from ts_guard_gates import (  # noqa: F401
    _GUARD,
    _NEWCOND,
    _STRINGS,
    _THROW,
    _vocab_hit_is_real,
    is_rejected_line,
    strip_literals,
)

_JS_EXT = re.compile(r"\.(js|jsx|mjs|cjs)$", re.I)
_TEST_SUFFIX = re.compile(
    r"\.(test|spec|suite|stories|mock|fixture|fixtures|e2e|bench|conf|config)\.(js|jsx|mjs|cjs)$"
    r"|(^|/)[\w.-]*(tests?|fixtures?|mocks?)\.(js|jsx|mjs|cjs)$"
    # PREFIX form: `test-injection.js` in ronomon/opened produced an
    # `assert(fs.existsSync('command_line_injection') === false)` "guard".
    r"|(^|/)(test|spec|mock|fixture|bench)[-_.][\w.-]*\.(js|jsx|mjs|cjs)$",
    re.I,
)
# Built/vendored output. `dist/x.js` is usually a COMPILED copy of `src/x.ts`, so
# including it both duplicates a record and credits generated code with the guard.
_BUILT_OR_VENDOR = re.compile(
    r"(^|/)(dist|build|out|lib|_bundles|umd|esm|cjs|amd|browser|coverage|node_modules"
    r"|vendor|vendors|third[_-]?party|externals|public|static|assets)/",
    re.I,
)
_MINIFIED = re.compile(r"\.min\.|[.-]bundle|\.pack\.|\bpolyfills?\b", re.I)
_SKIP_DIR = re.compile(
    r"(^|/)(test|tests|spec|specs|__tests__|__mocks__|__fixtures__|fixtures?|mocks?"
    r"|examples?|example|demo|demos|docs?|website|benchmark(s)?|e2e|cypress|scripts?)/",
    re.I,
)
# A generated file says so. Trusting the banner is cheaper and more reliable than
# guessing from the path.
_GENERATED_BANNER = re.compile(
    r"@generated|DO NOT EDIT|auto-?generated|generated by", re.I
)

# A control-flow keyword followed by parens is a CONDITION, not a declaration.
# Excluding these is what separates `async validate(token) {` from `if (cond) {`.
_KEYWORD_HEAD = re.compile(
    r"^\s*(if|for|while|switch|catch|return|do|else|with|typeof|new|await|throw|case)\b"
)
_SIGNATURE_FORM = re.compile(
    r"^\s*(?:static\s+)?(?:async\s+)?(?:function\s*\*?\s*)?[\w$]+\s*\([^;{]*\)\s*\{?\s*$"
)


def _is_js_signature(line):
    """A function or method DECLARATION, never a conditional."""
    if _KEYWORD_HEAD.match(line):
        return False
    if re.match(r"^\s*async\s+(?:function\b|[\w$]+\s*\()", line):
        return True
    return bool(_SIGNATURE_FORM.match(line))


# Derived by hand-inspecting 26 random candidates from the first harvest pass
# (12 genuine / 14 leaks). Each entry names the case that produced it, so a future
# reader can judge whether the rule is still earning its place.
_JS_EXTRA = [
    # `const csrf = require('../middleware/csrf');`  NodeBB/index.js
    # A CommonJS import in disguise: the shared `_IMPORT_EXPORT` gate anchors on a
    # line STARTING with `require(`, so an assignment form slips past it.
    ("commonjs_require", re.compile(r"^\s*(?:const|let|var)\s+[\w{},:\s]+=\s*require\s*\(")),

    # `}).catch(reject);`            roest01/node-pdf-image
    # `deferred[++resolved].reject(error);`   sveltejs/kit
    # `reject(outputs.stderr.join('').trim());`  omrilotan/async-git
    # Promise plumbing the shared gate misses: it only caught bare-identifier
    # rejects and `new Promise((resolve, reject)`.
    ("promise_plumbing_js", re.compile(
        r"^\s*\}?\)?\s*\.(catch|then|finally)\s*\(\s*reject\s*\)"
        r"|^\s*[\w.\[\]+]*\.?reject\s*\(.*\)\s*;?\s*$")),

    # `[p.basename(path), destination],`   eflexsystems/node-samba
    # An ARRAY literal element is data, exactly as an object literal is. The shared
    # `_OBJ_LITERAL` gate only covers `key: value`.
    ("array_literal_element", re.compile(r"^\s*\[[^\]]*\]\s*,\s*$")),

    # `if (e instanceof Parse.Error) {`   parse-community/parse-server
    # `_NAMESPACED_ERR` requires a `.errors.` segment, so a namespaced type ending
    # in `Error` is not matched. Error classification is not a security control.
    ("namespaced_error_class", re.compile(r"instanceof\s+\w+(?:\.\w+)*\.(?:Error|Exception)\b")),

    # `assert(typeof fn === 'function')`   thenables/thenify
    # `assert.ok(cmp(v1, "==", v1), ...)`  npm/node-semver
    # A type/shape assertion is an invariant check, not a security control. Only
    # asserts that reference a denylist or policy survive -- e.g. set-in's
    # `assert.ok(!POLLUTED_KEYS.includes(key), ...)`, which this does not match.
    ("type_assertion", re.compile(r"^\s*assert(?:\.\w+)?\s*\(\s*(?:typeof\s|\w+\s*\(.*\)\s*[,)])")),

    # `}).limit(batchSize).sort({ _id: 1 }).toArray();`  apostrophecms/apostrophe
    # A database query chain. `limit` is in the guard vocabulary, so paging code
    # scores as a resource control.
    ("db_query_chain", re.compile(r"\.(limit|skip|sort|toArray|lean|exec)\s*\(.*\)\s*\.")),

    # `maxDepth = Math.max(savedMaxDepth, maxDepth);`   parse-server
    # `? Math.max(Math.abs(numeric(n[2])), 1)`          brace-expansion
    # Arithmetic on a bound is a computation; the control is wherever that bound is
    # ENFORCED. A ternary fragment is also not a complete statement.
    ("arithmetic_or_fragment", re.compile(
        r"^\s*[\w.\[\]]+\s*=\s*Math\.(max|min|abs|floor|ceil)\b|^\s*[?:]\s*Math\.")),

    # `return res.sendStatus(200); // Adjusted from 404 ...`   tailot/taylored
    # Sending a response reports an outcome; it does not enforce one.
    ("http_response", re.compile(r"^\s*(?:return\s+)?res\.(sendStatus|status|send|json|end)\s*\(")),

    # --- second inspection pass (26 fresh candidates) ---------------------

    # `var width = Math.max(n[0].length, n[1].length)`   juliangruber/brace-expansion
    # The first arithmetic rule anchored on `name = Math.` and so missed the
    # DECLARATION form.
    ("arithmetic_decl", re.compile(r"^\s*(?:var|let|const)\s+[\w$]+\s*=\s*Math\.\w+\s*\(")),

    # `async function verifyIdToken({ id_token: token, id }, ...`  parse-server
    # `async validate(token) {`                                    strapi/recaptcha
    # Function and method signatures. The shared `_SIG_LINE` anchors on `function `
    # at the start, so an `async` prefix or a bare method name slips past.
    # NOTE: the first version of this rule was `[\w$]+\s*\(...\)\s*\{?$`, which
    # matches `if (cond) {` because `if` is a word followed by parens and a brace.
    # It destroyed 8 of 14 hand-judged genuine guards -- every conditional. The
    # keyword head must be excluded explicitly, which is clearer as a function.
    ("async_signature", _is_js_signature),

    # `.split(token + '*').join(token + '{0,' + max + '}')`  npm/node-semver
    # `subsupTokens.push(new Token(uSubsAndSups[lex.text]))`  KaTeX/Parser.js
    # `if (token === null) {`                                 protobufjs/parse.js
    # THE IMPORTANT ONE. `token` is in the guard vocabulary because it usually means
    # a credential -- but in a parser, lexer or tokenizer it means a LEXEME. Three of
    # twelve leaks in this pass came from parser code scoring as auth code. Handled
    # at file level in `vocab_ok_for_file`, since the word alone cannot be judged.
    ("lexer_string_build", re.compile(r"\.(split|join|push)\s*\(\s*[\w$]*[Tt]oken")),

    # --- third inspection pass (24 fresh candidates) ----------------------

    # `} else if (!!this.htmlMessage.jquery) { // Check if it is jQuery object`
    #   samschurter/materialize
    # The vocabulary hit ("Check") is in a TRAILING COMMENT. A comment describes;
    # it does not enforce. Handled in `vocab_outside_comment` because the line
    # itself is otherwise legitimate-looking.
    ("comment_only_vocab", lambda l: not _vocab_outside_comment(l)),

    # `if (!(buffer instanceof ArrayBuffer)) {`   sveltejs/devalue
    # `_BUILTIN_TYPE` lists Buffer but not ArrayBuffer / the typed arrays.
    ("builtin_binary_type", re.compile(
        r"instanceof\s+(ArrayBuffer|SharedArrayBuffer|DataView|Uint\d+Array"
        r"|Int\d+Array|Float\d+Array|BigInt64Array|BigUint64Array)\b")),
]

_TRAILING_COMMENT = re.compile(r"(//|/\*).*$")


def _vocab_outside_comment(line):
    """Does the guard vocabulary survive with comments removed?

    `} else if (!!this.htmlMessage.jquery) { // Check if it is jQuery object`
    scores only because the word "Check" appears in prose after `//`.
    """
    if not _GUARD.search(line):
        return True                      # nothing to attribute; other gates decide
    stripped = _TRAILING_COMMENT.sub("", line)
    return bool(_GUARD.search(strip_literals(stripped)))

# Files whose domain redefines a vocabulary word. In a parser, `token` is a lexeme,
# so a hit on `token` alone carries no security meaning there.
_PARSER_FILE = re.compile(
    r"(^|/)[\w.-]*(parser?|lexer|tokeni[sz]er|semver|grammar|ast|syntax)[\w.-]*"
    r"\.(js|jsx|mjs|cjs)$", re.I
)
_TOKEN_ONLY = re.compile(r"\btoken\b", re.I)


def vocab_ok_for_file(line, path):
    """Reject a vocabulary hit that only means something in another domain.

    `token` in `Parser.js` / `semver.js` / `parse.js` is a lexeme, not a credential.
    Only fires when `token` is the ONLY thing making the line score, so a real
    auth check in a parser file still survives.
    """
    if not path or not _PARSER_FILE.search(path):
        return True
    if not _TOKEN_ONLY.search(line):
        return True
    without = _TOKEN_ONLY.sub(" ", line)
    return bool(_GUARD.search(without))


def is_js_source(path):
    """A real, hand-written JavaScript source file we would learn from."""
    p = (path or "").strip()
    if not _JS_EXT.search(p):
        return False
    if _TEST_SUFFIX.search(p):
        return False
    if _BUILT_OR_VENDOR.search(p) or _MINIFIED.search(p):
        return False
    if _SKIP_DIR.search(p):
        return False
    return True


def looks_generated(blob):
    """True if the added lines carry a generated-file banner."""
    return bool(_GENERATED_BANNER.search(blob or ""))


def is_rejected_js_line(line):
    """TS line gates first, then any JS-specific rule observed since."""
    why = is_rejected_line(line)
    if why:
        return why
    for name, rule in _JS_EXTRA:
        hit = rule(line) if callable(rule) else bool(rule.search(line))
        if hit:
            return name
    return None


def pick_js_guard(added, path=None):
    """Highest-signal added line, requiring a real security-vocabulary hit.

    Mirrors `pick_ts_guard`: score 2 for vocabulary, 1 for being a new conditional,
    require >= 2 so that merely being an `if` is not enough, prefer the LONGEST
    qualifying line (short candidates are truncated wrapped conditions), and demote
    `throw` so the check wins over its consequence.
    """
    scored, throws = [], []
    for l in added:
        if is_rejected_js_line(l):
            continue
        s = 0
        if _GUARD.search(l) and _vocab_hit_is_real(l) and vocab_ok_for_file(l, path):
            s += 2
        if _NEWCOND.match(l):
            s += 1
        if s < 2:
            continue
        (throws if _THROW.match(l) else scored).append((s, len(l.strip()), l.strip()))
    pool = scored or throws
    if not pool:
        return None
    pool.sort(key=lambda x: (-x[0], -x[1]))
    return pool[0][2]
