# ============================================================
# mine_clean_code.py
#
# Mines self-contained Python functions from well-audited
# open-source libraries to use as clean-code SCAN pairs.
#
# Strategy:
#   - ALLOWLIST of mature libraries (no pen-test tools, no
#     scanners, no intentionally-vulnerable apps)
#   - Skip tests/, examples/, docs/, benchmarks/
#   - Per-function blacklist: eval, exec, shell=True,
#     pickle.load, etc.
#   - Skip functions whose docstring/comments mention
#     "vulnerable", "unsafe", "exploit", "DEPRECATED"
#   - Size 3-30 lines, 80-1500 chars
#   - Cap at 800 to avoid flooding the SCAN slice
#
# Output: data/sft/clean_code_mined.jsonl
# ============================================================
import os
import ast
import json
import random

random.seed(11)

REPOS_ROOT = os.path.join("data", "pretrain", "repos")
SEC_REPOS_ROOT = os.path.join("data", "pretrain", "security_repos")
OUTPUT = os.path.join("data", "sft", "clean_code_mined.jsonl")
TARGET_PAIRS = 800

# (repo_dir, subpath_within_repo). Subpath narrows mining to the
# library source proper, skipping vendored deps, examples, etc.
ALLOWLIST = [
    (REPOS_ROOT, "aiohttp-master/aiohttp"),
    (REPOS_ROOT, "bottle-master"),
    (REPOS_ROOT, "celery-main/celery"),
    (REPOS_ROOT, "click-main/src"),
    (REPOS_ROOT, "cryptography-main/src"),
    (REPOS_ROOT, "django-main/django"),
    (REPOS_ROOT, "django-allauth-main/allauth"),
    (REPOS_ROOT, "django-oauth-toolkit-master/oauth2_provider"),
    (REPOS_ROOT, "django-rest-framework-main/rest_framework"),
    (REPOS_ROOT, "fastapi-master/fastapi"),
    (REPOS_ROOT, "flask-main/src/flask"),
    (REPOS_ROOT, "httpx-master/httpx"),
    (REPOS_ROOT, "jinja-main/src"),
    (REPOS_ROOT, "marshmallow-dev/src"),
    (REPOS_ROOT, "paramiko-main/paramiko"),
    (REPOS_ROOT, "peewee-master"),
    (REPOS_ROOT, "Pillow-main/src"),
    (REPOS_ROOT, "pydantic-main/pydantic"),
    (REPOS_ROOT, "requests-main/src/requests"),
    (REPOS_ROOT, "sqlalchemy-main/lib"),
    (REPOS_ROOT, "starlette-main/starlette"),
    (REPOS_ROOT, "urllib3-main/src"),
    (REPOS_ROOT, "werkzeug-main/src"),
    (SEC_REPOS_ROOT, "authlib-main/authlib"),
    (SEC_REPOS_ROOT, "oauthlib-master/oauthlib"),
    (SEC_REPOS_ROOT, "pyjwt-master/jwt"),
]

# Directory parts to skip when walking (case-insensitive match on any component)
SKIP_DIR_PARTS = {
    "tests", "test", "testing",
    "examples", "example", "samples",
    "docs", "doc", "documentation",
    "benchmarks", "benchmark", "perf",
    "fixtures", "fixture",
    "migrations",   # autogenerated, often noisy
    "vendor", "third_party", "thirdparty",
    "node_modules", ".git", ".tox", "__pycache__",
}

# Patterns inside function source that disqualify it.
BLACKLIST_PATTERNS = [
    "eval(", "exec(",
    "os.system(", "os.popen(",
    "subprocess.Popen", "subprocess.call", "subprocess.run", "subprocess.check_output", "subprocess.check_call",
    "pickle.load", "pickle.loads", "marshal.loads", "marshal.load",
    "__import__(", "compile(",
    "yaml.load(",    # the unsafe form — we can't easily tell if Loader= is passed
    "input(",        # interactive — odd for libraries; skip
    "shell=True",
    "verify=False",  # disabled TLS verification
    "ssl.CERT_NONE",
    "MD5", "md5(", "sha1(", "SHA1",   # weak hashes
    "DES(", "RC4",                    # weak ciphers
    "random.random(", "random.randint(", "random.choice(",  # non-crypto random — risky for security contexts
    "// nosec", "# nosec",  # someone explicitly suppressed a warning here
]

# Words in docstrings/comments that suggest this function isn't a clean example.
SUSPICIOUS_DOC_WORDS = [
    "vulnerable", "vulnerability", "exploit", "attack", "attacker",
    "insecure", "unsafe", "dangerous",
    "deprecated", "do not use", "todo: security", "fixme: security",
    "xss", "csrf", "sql injection", "command injection", "path traversal",
    "rce", "buffer overflow",
]

# Varied response phrasings for the assistant message.
SAFE_RESPONSES = [
    "No vulnerabilities detected. The function is a self-contained helper with no obvious unsafe operations.",
    "No security issues found. The code performs data manipulation without invoking dangerous APIs.",
    "Code review: safe. No use of eval, shell execution, or unsafe deserialization.",
    "No security flaws identified. Internal utility function with limited attack surface.",
    "No vulnerabilities detected. Pure logic without external I/O concerns.",
    "No security issues found. The function relies on standard, well-typed operations.",
    "No vulnerabilities detected. Input is handled through normal language constructs only.",
    "Code review: safe. No injection, no deserialization, no privilege-affecting calls.",
]


def is_skip_path(path: str) -> bool:
    """True if any path component matches a skipped directory part."""
    parts = path.replace("\\", "/").split("/")
    for p in parts:
        if p.lower() in SKIP_DIR_PARTS:
            return True
        if p.lower().startswith("test_") or p.lower().endswith("_test.py"):
            return True
    return False


def get_function_source(source: str, node: ast.AST) -> str:
    """Best-effort extract function source from line numbers."""
    if not hasattr(node, "lineno") or not hasattr(node, "end_lineno"):
        return ""
    lines = source.splitlines()
    if node.end_lineno is None or node.lineno is None:
        return ""
    return "\n".join(lines[node.lineno - 1 : node.end_lineno])


def passes_filters(code: str, node: ast.AST) -> bool:
    if not code.strip():
        return False

    line_count = code.count("\n") + 1
    if line_count < 3 or line_count > 30:
        return False
    if len(code) < 80 or len(code) > 1500:
        return False

    code_lower = code.lower()
    for pat in BLACKLIST_PATTERNS:
        if pat.lower() in code_lower:
            return False

    # Check docstring + comments for suspicious words
    doc_text = ""
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
        doc = ast.get_docstring(node) or ""
        doc_text = doc.lower()
    # Also scan comments inside the snippet
    for line in code.split("\n"):
        s = line.strip()
        if s.startswith("#"):
            doc_text += " " + s.lower()
    for word in SUSPICIOUS_DOC_WORDS:
        if word in doc_text:
            return False

    return True


def collect_functions(root_dir: str) -> list[str]:
    """Walk root_dir, return list of clean function source strings."""
    found = []
    if not os.path.isdir(root_dir):
        return found

    for dirpath, dirnames, filenames in os.walk(root_dir):
        # Prune skipped dirs in-place so we never descend into them
        dirnames[:] = [d for d in dirnames if d.lower() not in SKIP_DIR_PARTS
                       and not d.lower().startswith("test_")]

        if is_skip_path(dirpath):
            continue

        for fname in filenames:
            if not fname.endswith(".py"):
                continue
            if fname.lower().startswith("test_") or fname.lower().endswith("_test.py"):
                continue
            if fname == "conftest.py":
                continue

            fullpath = os.path.join(dirpath, fname)
            try:
                with open(fullpath, "r", encoding="utf-8", errors="ignore") as f:
                    source = f.read()
                tree = ast.parse(source)
            except (SyntaxError, ValueError):
                continue

            for node in ast.walk(tree):
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    code = get_function_source(source, node)
                    if passes_filters(code, node):
                        found.append(code)
    return found


def main():
    print(f"Mining clean Python functions from {len(ALLOWLIST)} allowlisted repos...")
    print()

    all_funcs = []
    for root, subpath in ALLOWLIST:
        target = os.path.join(root, *subpath.split("/"))
        funcs = collect_functions(target)
        print(f"  {subpath:55s} {len(funcs):>6,} functions")
        all_funcs.extend(funcs)

    print(f"\nTotal candidate functions: {len(all_funcs):,}")

    # Deduplicate by code text
    unique = list(dict.fromkeys(all_funcs))
    print(f"After dedup: {len(unique):,}")

    # Sample down to TARGET_PAIRS
    if len(unique) > TARGET_PAIRS:
        sampled = random.sample(unique, TARGET_PAIRS)
    else:
        sampled = unique
    print(f"Sampled to: {len(sampled):,}")

    # Build pairs
    pairs = []
    for code in sampled:
        response = random.choice(SAFE_RESPONSES)
        pairs.append({
            "messages": [
                {"role": "user", "content": f"<SCAN>\n{code}\n</SCAN>"},
                {"role": "assistant", "content": response}
            ]
        })

    random.shuffle(pairs)

    with open(OUTPUT, "w", encoding="utf-8") as f:
        for p in pairs:
            f.write(json.dumps(p) + "\n")

    print(f"\nSaved {len(pairs):,} pairs to {OUTPUT}")


if __name__ == "__main__":
    main()
